### ISSUE TITLE
[Bug] entry state function _on_enter_state() doesn't executing

### ISSUE THREAD

**Issue by boruok** [godot-addons/godot-finite-state-machine#12]
I've noticed that since previous version fsm doesn't execute _on_enter_state() function at first cycle. But in next transition that function been called on each transitions. Is that supposed to be?

**Comment by brandonlamb** [comment]
Oh, you know what, that was a dumb default to set (false) on the two flags for enter/exit enabled, crap. They should probably be true by default.

**Comment by brandonlamb** [comment]
Closed via #13

**Comment by boruok** [comment]
no still doesn't work. Let me explain better:
according the example Enemy-Node have entry state named IdleState with _on_enter_state() within. I expected that statemachine execute a_on_enter_state() immediatly when statemachine is instantiated. Here example shows how statemachine executes a_on_enter_state():
| smf.create()            | idleState | patrolState         | idleState | patrolState         | idleState |
|-------------------------|-----------|---------------------|-----------|---------------------|-----------|
| "current_state": "idle" | not       | transtition("idle") | called    | transtition("idle") | called    |

**Comment by brandonlamb** [comment]
Oh, I'm thinking maybe the issue is setting the initial current_state to null, then transitioning from null to first idle_state, which should then run the first on_enter. It makes sense this is not called on instantiating *IF* current_state is defined as idle at instantiating, because the handlers are only called during transition, there is no transition on instantiating unless its null first

null => transition(idle) => idle._on_enter_state => idle.process => transition(patrol) => idle._on_exist => patrol._on_enter => patrol.process

**Comment by boruok** [comment]
fixed by #19
